// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.aboutConfig.showWarning", false);
user_pref("firefoxpwa.openOutOfScopeInDefaultBrowser", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("sidebar.old-sidebar.has-used", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"close-page-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"notifications-button\",\"site-info\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reader-view-button\",\"copy-link-button\",\"send-to-device-button\",\"open-in-browser-button\",\"mute-button\",\"unified-extensions-button\",\"tracking-protection-button\",\"identity-button\",\"permissions-button\",\"notifications-button\",\"close-page-button\",\"back-button-ffpwa\",\"forward-button-ffpwa\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"vertical-tabs\",\"toolbar-menubar\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
