# General Settings
hide_window_decorations yes
enable_audio_bell no
shell /usr/bin/fish
cursor_shape block
shell_integration no-cursor

# Fonts
font_family CaskaydiaCove Nerd Font
bold_font        SauceCodePro Nerd Font
italic_font      SauceCodePro Nerd Font 
bold_italic_font SauceCodePro Nerd Font 
font_size 10

# Window layout
window_padding_width 1

# Color scheme (OneDark)
foreground #abb2bf
background #1E2127
cursor #cccccc
color0 #1E2127
color1 #e06c75
color2 #98c379
color3 #d19a66
color4 #61afef
color5 #c678dd
color6 #56b6c2
color7 #e6efff
color8 #5c6370
color9 #e06c75
color10 #98c379
color11 #d19a66
color12 #61afef
color13 #c678dd
color14 #56b6c2
color15 #828791
selection_foreground #282c34
selection_background #979eab
