add_newline = true
format = "$directory$git_branch$git_status$character"
right_format = """$all"""

[character]
success_symbol = "[»](green)"
error_symbol = "[»](red)"
vicmd_symbol = "[«](green)"

[directory]
format = "[$path]($style)[  ](bold blue)[$read_only](bold #f9e2af)($read_only_style) "
truncation_length = 1
home_symbol = "  "
read_only = "  "

[git_branch]
style = "bold #89b4fa"

[git_metrics]
disabled = false

[git_status]
ahead = " ⇡ ${count}"
diverged = "⇕ ⇡ ${ahead_count} ⇣ ${behind_count}"
behind = "⇣ ${count}"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#f5c2e7"

[sudo]
disabled = true
