[preferred]
default=gnome;gtk;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=gnome-keyring;

# Change from default: Prefer gtk here to avoid the accent color set in GNOME Settings
org.freedesktop.impl.portal.Settings=gtk;
