return {
  ActiveLSP1 = "",
  ActiveTS1 = "",
  Bar = "|",
  BarBold = "┃",
  BookMark = "",
  Change = "",
  DefaultFile1 = "",
  Directory = "",
  EvilIcon = "",
  FileModified1 = "",
  FileNew = "",
  FileRecent = "",
  Find = "",
  GitBranch = "",
  GitBranch1 = "",
  Mode = "",
  Plugin = "",
  Project = "",
  Reload = "",
  Space = "",
  Target = "",
}
