-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 201NTJJBJ076",
  mode = "1920x1080@119.98",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x1521",
  disabled = true,
})
