#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

# -p is needed as we use prompts, alternative programs have to handle prompts well.

DMENU="rofi -dmenu -i -p"

PDF_VIEWER="zathura"

# DMTERM="st -e"
DMTERM="alacritty -e"

DMEDITOR="emacsclient -cn -a emacs"
# DMEDITOR="${DMTERM} vim"

# TODO: Rename this variable to something more traditional
logout_locker='betterlockscreen -l blur --off 30'
# logout_locker='dm-tool lock'

# This case statement lets you change what the DMENU variable is for different scripts, so if you
# want a unique variable for each script you can
# syntax is as follows:
# "<ending-of-script>") DMENU="your variable here"
# *) should be left blank, global variables are defined above

# include -p in standard dmenu as we use prompts by default
case "${0##*-}" in
#  "colpick") DMENU="dmenu -i -p";;
 # "confedit") DMENU="dmenu -i -l 30 -p";;
 "kill") DMENU="dmenu -i -l 15 -p";;
 "wifi") DMENU="dmenu -i -l 15 -p";;
#  "youtube") DMBROWSER="firefox";;
  *);;
esac

# "${0##*-}" means grab the 0th argument (which is always the path to the program) starting from the
# last dash. This gives us the word after the - which is what we are searching for in the case
# statement. ie dm-man -> man

# An awk equivalent is:
# awk -F"-" '{print $NF}'
# Sadly cut has no easy equivalent

# TODO: Move almost all of these variables into the case statement
# TODO: Make some of the more useful ones general variables
# IE a pictures directory, an audio directory, config locations, etc

# dm-setbg
setbg_dir="${HOME}/Pictures/Wallpapers"
# Set this to 1 if you want to use imv and wayland, 0 if you want to use sxiv
# Note that sxiv is X11 only, you need to mark the image you want to use.
use_imv=0

# dm-maim
maim_dir="${HOME}/Pictures/Screenshots"
maim_file_prefix="maim"

# dm-confedit
declare -A confedit_list
confedit_list[confedit]="$HOME/.config/dmscripts/config"
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit_list[awesome]="$HOME/.config/awesome/rc.lua"
confedit_list[bash]="$HOME/.bashrc"
confedit_list[doom emacs config.el]="$HOME/.config/doom/config.el"
confedit_list[doom emacs config.org]="$HOME/.config/doom/config.org"
confedit_list[doom emacs init.el]="$HOME/.config/doom/init.el"
confedit_list[doom emacs packages.el]="$HOME/.config/doom/packages.el"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
confedit_list[fish]="$HOME/.config/fish/config.fish"
confedit_list[neovim]="$HOME/.config/nvim/init.lua"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[xmobar]="$HOME/.config/xmobar/tokyonight-xmobarrc"
confedit_list[xmonad]="$HOME/.config/xmonad/xmonad.hs"
confedit_list[xresources]="$HOME/.Xresources"

# dm-colpick config
declare -A colpick_list
#
# Tokyonight
#
# colpick_list[background]="#1a1b26"
# colpick_list[foreground]="#a9b1d6"
# colpick_list[color1-black]="#32344a"
# colpick_list[color2-red]="#f7768e"
# colpick_list[color3-green]="#9ece6a"
# colpick_list[color4-orange]="#e0af68"
# colpick_list[color5-blue]="#7aa2f7"
# colpick_list[color6-magenta]="#ad8ee6"
# colpick_list[color7-cyan]="#449dab"
# colpick_list[color8-white]="#787c99"
# colpick_list[color9-black]="#444b6a"
# colpick_list[color10-red]="#ff7a93"
# colpick_list[color11-green]="#b9f27c"
# colpick_list[color12-orange]="#ff9e64"
# colpick_list[color13-blue]="#7da6ff"
# colpick_list[color14-magenta]="#bb9af7"
# colpick_list[color15-cyan]="#0db9d7"
# colpick_list[color16-white]="#acb0d0"
#
# Catppuccin
#
colpick_list[background]="#1e1e2e"
colpick_list[foreground]="#cdd6f4"
colpick_list[color1-black]="#45475a"
colpick_list[color2-red]="#f38ba8"
colpick_list[color3-green]="#a6e3a1"
colpick_list[color4-yellow]="#f9e2af"
colpick_list[color5-blue]="#89b4fa"
colpick_list[color6-magenta]="#f5c2e7"
colpick_list[color7-cyan]="#94e2d5"
colpick_list[color8-white]="#bac2de"
colpick_list[color9-black]="#585b70"
colpick_list[color10-red]="#f38ba8"
colpick_list[color11-green]="#a6e3a1"
colpick_list[color12-yellow]="#f9e2af"
colpick_list[color13-blue]="#89b4fa"
colpick_list[color14-magenta]="#f5c2e7"
colpick_list[color15-cyan]="#94e2d5"
colpick_list[color16-white]="#a6adc8"

# dm-weather config
declare -A weather_location
weather_location[Basti]="Basti"
weather_location[Bengaluru]="Bengaluru"
weather_location[Delhi]="Delhi"
weather_opts="m" # Always use metric units (celsius)
# weather_opts="u" # Always use US units (fahrenheit)
# see: https://github.com/chubin/wttr.in
