# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

[shell]
disabled = false
bash_indicator = ""
fish_indicator = "󰈺"

[os]
disabled = false
format = "$symbol  "
symbols.Arch = ""
symbols.Fedora = ""
symbols.openSUSE = ""
symbols.Ubuntu = ""
