-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + CTRL + D")
hl.bind("SUPER + CTRL + D", hl.dsp.exec_cmd("dms ipc call discord toggleDeafen"), { description = "Discord Deafen" })
hl.unbind("SUPER + CTRL + M")
hl.bind("SUPER + CTRL + M", hl.dsp.exec_cmd("dms ipc call discord toggleMute"), { description = "Discord Mute" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dms ipc call defaultApp mail"), { description = "Default Mail: Open" })
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("dms ipc call spotlight toggleQuery !"), { description = "Show Open Windows" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc call defaultApp browser"), { description = "Default Web Browser: Open" })
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("code"), { description = "VS Code" })
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("neovide"), { description = "Neovide" })
hl.unbind("SUPER + Print")
hl.bind("SUPER + Print", hl.dsp.exec_cmd("gpu-screen-recorder-gtk"), { description = "Screen Recorder" })
hl.unbind("SUPER + SHIFT + D")
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("flatpak run com.discordapp.Discord"), { description = "Discord" })
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("zeditor"), { description = "Zed Editor" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.exec_cmd("dms ipc call defaultApp fileManager"), { description = "Default File Manager: Open" })
