-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 1,
		gaps_out = 3,
		border_size = 2,
		resize_on_border = true,
	},
	decoration = {
		rounding = 5,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
