-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Chimei Innolux Corporation 0x1521", mode = "1920x1080@144.003", position = "384x0", scale = 1.25, vrr = 0 })
hl.monitor({ output = "desc:LG Electronics LG ULTRAGEAR 201NTJJBJ076", disabled = true })
