#!/usr/bin/env bash

# Tell this script to exit if there are any errors
set -oue pipefail

# Source utils
UTILS_DIR="$(dirname "$(readlink -f "$0")")/utils"
source "$UTILS_DIR/string-formatter"    # string formatters to add colors and bling
source "$UTILS_DIR/confirmation-prompt" # yes/no confirmation prompt

# Display script header
printf "\n"
ohai " " "${tty_yellow}############### APPLYING DCONF SETTINGS ###############"
printf "\n"

# Add confirmation prompt to continue/exit script based on user response
prompt

# Dconf file path relative to this script
DCONF_FILE="$UTILS_DIR/../../dconf.ini"
ohai "Loading writable dconf changes..."
dconf load -f / < $DCONF_FILE

# Signal end
printf "\n${tty_green}Dconf settings loaded!\n"
