#!/usr/bin/env bash

# Tell this script to exit if there are any errors
set -oue pipefail

# Source utils
UTILS_DIR="$(dirname "$(readlink -f "$0")")/utils"
source "$UTILS_DIR/string-formatter"    # string formatters to add colors and bling
source "$UTILS_DIR/confirmation-prompt" # yes/no confirmation prompt

# Display script header
printf "\n"
ohai " " "${tty_yellow}############### SETTING UP NEOVIM CONFIG ###############"
printf "\n"

# Add confirmation prompt to continue/exit script based on user response
prompt

# Set neovim directory
NVIM_DIR="$HOME/.config/nvim"

# Clone neovim config if it doesn't exist
if [[ ! -d "$NVIM_DIR" ]]; then
  ohai "Cloning neovim config..."
  git clone https://github.com/shans10/astronvim-config.git $NVIM_DIR
else
  ohai "" "${tty_yellow}Directory already exists, delete it and try again. Exiting..."
  printf "\n"
fi

# Signal end
printf "${tty_green}DONE!\n"
